version: "3" 
services:

    web:
        image: nginx
        ports:
          - "80:80"
        volumes:
          - "./nginx/:/etc/nginx/conf.d/"
          - "./app/public/:/var/www/html/public/"


